sudo: required
language: python
jdk: openjdk8
services: docker
python: '3.7'
cache: pip
matrix:
  fast_finish: true

before_install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo conda update conda --yes

install:
  # use the conda env to install all dependencies
  - mkdir -p $HOME/conda
  - conda create env -p $HOME/conda/hicpro -f envs/conda.yml
  - source activate $HOME/hicpro

script:
  # Get test data
  - wget https://zerkalo.curie.fr/partage/HiC-Pro/HiCPro_testdata.tar.gz && tar -zxvf HiCPro_testdata.tar.gz
  - /bin/rm -f HiCPro_testdata.tar.gz
  - time HiC-Pro -i test_data -o results -c config-hicpro.txt
