sudo: false
language: python
jdk: openjdk8
services: docker
python: '3.7'
cache: pip
matrix:
  fast_finish: true

before_install:
  # install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda


install:
  # use the conda env to install all dependencies
  - mkdir -p $HOME/conda
  - conda env create -p $HOME/conda/hicpro -f envs/conda.yml
  - export PATH=$HOME/conda/hicpro/bin:$PATH
  # Install HiC-Pro
  - make configure
  - make install

script:
  # Get test data
  - wget https://zerkalo.curie.fr/partage/HiC-Pro/HiCPro_testdata.tar.gz && tar -zxvf HiCPro_testdata.tar.gz
  - /bin/rm -f HiCPro_testdata.tar.gz
  - INSTALLED_HICPRO_VERSION=$(find /usr/local/bin -name HiC-Pro | xargs dirname)
  - time $INSTALLED_HICPRO_VERSION/HiC-Pro -i test_data -o $HOME/results -c config-hicpro.txt
