sudo: required
language: python
python: '3.7'
cache: pip
matrix:
  fast_finish: true

before_install:
  # install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda


install:
  # use the conda env to install all dependencies
  - mkdir -p $HOME/conda
  - conda env create -p $HOME/conda/hicpro -f envs/conda.yml
  - export PATH=$HOME/conda/hicpro/bin:$PATH
  # Install HiC-Pro
  - mkdir $HOME/apps
  - make configure prefix=$HOME/apps
  - make install

script:
  # Get test data
  - wget https://zerkalo.curie.fr/partage/HiC-Pro/hicpro_testop_travis.tar.gz && tar -zxvf hicpro_testop_travis.tar.gz
  - /bin/rm -f hicpro_testop_travis.tar.gz
  # Run HiC-Pro
  - INSTALLED_HICPRO_VERSION=$(find $HOME/apps -name HiC-Pro | xargs dirname)
  - time $INSTALLED_HICPRO_VERSION/HiC-Pro -i test_data -o $HOME/results -c config_testop_yeast.txt

